# Generated by Django 3.2.9 on 2022-01-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('image', models.ImageField(upload_to='images/')),
                ('author', models.CharField(default='Author name..', max_length=100)),
                ('year_published', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(default='Title of the book', max_length=100)),
                ('price', models.IntegerField(blank=True, default='Price in dollars..', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
