# Generated by Django 3.0.8 on 2022-01-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NormalUser',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_normal_user',
            new_name='is_customer',
        ),
    ]
