# Generated by Django 3.2.9 on 2022-01-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('image', models.ImageField(upload_to='images/')),
                ('author', models.TextField(default='Author name..')),
                ('year_published', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(default='Title of the book')),
            ],
        ),
    ]
