# Generated by Django 3.2.9 on 2022-01-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(blank=True, default='Price in dollars..', null=True),
        ),
    ]
